baseURL = "http://seunlanlege.github.io"
languageCode = "en-us"
title = "Seun Lanlege - Software Engineer"
theme = "dimension"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Seun Lanlege"
  description = "Just university another drop out that loves writing code."

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/seunlanlege"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/seunlanlege"

